apiVersion: apps/v1
kind: Deployment
metadata:
  name: selforderhome
  namespace: tutorial
  labels:
    app: selforderhome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selforderhome
  template:
    metadata:
      labels:
        app: selforderhome
    spec:
      containers:
        - name: selforderhome
          image: hyeonwoo.azurecr.io/selforderhome:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
