server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: SelfOrder
          uri: http://localhost:8081
          predicates:
            - Path=/selfOrders/** 
        - id: Payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: Store
          uri: http://localhost:8083
          predicates:
            - Path=/stores/** 
        - id: SelfOrderHome
          uri: http://localhost:8084
          predicates:
            - Path= /selfOrderHomes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: SelfOrder
          uri: http://SelfOrder:8080
          predicates:
            - Path=/selfOrders/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: Store
          uri: http://Store:8080
          predicates:
            - Path=/stores/** 
        - id: SelfOrderHome
          uri: http://SelfOrderHome:8080
          predicates:
            - Path= /selfOrderHomes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
